### ISSUE TITLE
Support dots in identifiers

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metacalc#19]
Here is a case to be supported

```js
  const sheet = new Sheet();
  sheet.cells['item1.price'] = 100;
  sheet.cells['item2.price'] = 200;
  sheet.cells['item3.price'] = 300;
  sheet.cells['total'] = '=item1.price + item2.price + item3.price';
  test.strictSame(sheet.values['total'], 600);
```

Now it result:
```
Node v14.20.0 (v8 8.4.371.23-node.87):
Simple expressions .................................... 3/3
Expression chain ...................................... 2/2
JavaScript Math ....................................... 8/8
Prevent arbitrary js code execution ................... 7/7
Non-table identifiers ................................. 0/1
  not ok fail
    --- wanted
    +++ found
    -[null]
    +{
    +  "message": "Cannot read property 'price' of undefined"
    +  "name": "TypeError"
    +  "stack": "TypeError: Cannot read property 'price' of undefined
    +    at total:2:13
    +    at Object.getValue [as get] (metacalc/lib/sheet.js:22:10)
    +    at ImperativeTest.func (metacalc/test/unit.js:60:31)
    +    at ImperativeTest.runNow (metatests/lib/imperative-test.js:893:22)
    +    at Domain.<anonymous> (metatests/lib/imperative-test.js:875:14)
    +    at Domain.run (domain.js:378:15)
    +    at metatests/lib/imperative-test.js:874:18
    +    at processTicksAndRejections (internal/process/task_queues.js:77:11)"
    +}
    message: Promise rejection
    severity: fail
    type: fail
    at:
      file: /home/marcus/Dropbox/Metarhia/metacalc/test/unit.js
    stack: |
      processTicksAndRejections (internal/process/task_queues.js:95:5)

FAILED test 5
Failed 1/5 tests, 80.00% okay
npm ERR! Test failed.  See above for more details.
```

**Comment by Eternal-Rise** [comment]
Hello! The solution here is to make deep objects or has another approach?

**Comment by tshemsedinov** [comment]
We can implement it adding proxies. sheet.cells['item1'] -> Proxy instance with hook to read property `item1.price` @Eternal-Rise
